apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: banking-app
type: Opaque
stringData:
  ACCOUNT_SVC_URL: "http://account-service:3002"
 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: banking-app
data:
  PORT: "3004"
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: yaswanthreddy1602/payment-service:v1
          ports:
            - containerPort: 3004
          envFrom:
            - secretRef:
                name: payment-secret
            - configMapRef:
                name: payment-config
          startupProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 5
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: banking-app
spec:
  selector:
    app: payment
  ports:
    - port: 3004
      targetPort: 3004
  type: ClusterIP
