apiVersion: v1
kind: Pod
metadata:
  name: safe-pod
  namespace: secure-ns
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - name: nginx
    image: docker.io/library/nginx:latest
    ports:
    - containerPort: 8080
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
